#!/usr/bin/env python3
"""ML-DSA-65 tests: C-reference KAT + self-consistency + benchmarks.

KAT fixture: /tmp/dil/mldsa65_kat.json, generated by katgen (compiled from
pq-crystals/dilithium ref, DILITHIUM_MODE=3) with
  seed = 0001...1f, rnd = a0a1...bf, msg = "EXCAL-MLDSA65-KAT-VECTOR-01".
"""
import json
import os
import random
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mldsa

KAT = json.load(open("/tmp/dil/mldsa65_kat.json"))
KAT_MSG = bytes.fromhex(KAT["msg"])  # json stores msg hex-encoded
PASS = []


def check(name, cond):
    PASS.append((name, bool(cond)))
    print(("PASS " if cond else "FAIL ") + name)
    if not cond:
        raise SystemExit("FAILED: " + name)


def test_kat_keygen():
    seed = bytes.fromhex(KAT["seed"])
    pk, sk = mldsa.keygen(seed)
    check("kat pk", pk.hex() == KAT["pk"])
    check("kat sk", sk.hex() == KAT["sk"])


def test_kat_sign():
    seed = bytes.fromhex(KAT["seed"])
    rnd = bytes.fromhex(KAT["rnd"])
    msg = KAT_MSG
    _, sk = mldsa.keygen(seed)
    sig = mldsa.sign(sk, msg, rnd)
    check("kat sig", sig.hex() == KAT["sig"])


def test_kat_verify():
    pk = bytes.fromhex(KAT["pk"])
    sig = bytes.fromhex(KAT["sig"])
    msg = KAT_MSG
    check("kat verify ok", mldsa.verify(pk, msg, sig) is True)
    bad = bytearray(sig)
    bad[100] ^= 1
    check("kat verify mutated", mldsa.verify(pk, msg, bytes(bad)) is False)
    badpk = bytearray(pk)
    badpk[10] ^= 1
    check("kat verify wrong pk", mldsa.verify(bytes(badpk), msg, sig) is False)


def test_self_consistency():
    rng = random.Random(1234)
    for trial in range(3):
        seed = bytes(rng.randrange(256) for _ in range(32))
        rnd = bytes(rng.randrange(256) for _ in range(32))
        pk, sk = mldsa.keygen(seed)
        msg = b"EXCAL trial %d" % trial
        sig = mldsa.sign(sk, msg, rnd)
        check("self verify %d" % trial, mldsa.verify(pk, msg, sig) is True)
        check("self wrong msg %d" % trial,
              mldsa.verify(pk, b"tampered", sig) is False)


def test_ntt_roundtrip():
    rng = random.Random(99)
    p = [rng.randrange(mldsa.Q) for _ in range(256)]
    check("ntt roundtrip", mldsa.invntt(mldsa.ntt(p)) == p)


def test_decompose_identity():
    rng = random.Random(7)
    for _ in range(2000):
        a = rng.randrange(mldsa.Q)
        a1, a0 = mldsa._decompose(a)
        if not (0 <= a1 < 16 and a == (a1 * 2 * mldsa.GAMMA2 + a0) % mldsa.Q
                and -(mldsa.Q - 1) // 2 <= a0 <= (mldsa.Q - 1) // 2):
            check("decompose identity", False)
    check("decompose identity", True)


def test_pack_roundtrips():
    rng = random.Random(5)
    for i in range(6):
        p = [rng.randrange(1024) for _ in range(256)]
        check("t1 pack %d" % i, mldsa._unpack_t1(mldsa._pack_t1(p)) == p)
    for i in range(6):
        p = [rng.randrange(-4096, 4097) for _ in range(256)]
        check("t0 pack %d" % i, mldsa._unpack_t0(mldsa._pack_t0(p)) == p)
    for i in range(5):
        p = [rng.randrange(-4, 5) for _ in range(256)]
        check("eta pack %d" % i, mldsa._unpack_eta(mldsa._pack_eta(p)) == p)
    for i in range(5):
        p = [rng.randrange(-mldsa.GAMMA1 + 1, mldsa.GAMMA1 + 1)
             for _ in range(256)]
        check("z pack %d" % i, mldsa._unpack_z(mldsa._pack_z(p)) == p)


def test_bench():
    seed = bytes(range(32))
    t = time.time()
    pk, sk = mldsa.keygen(seed)
    kg = time.time() - t
    t = time.time()
    sig = mldsa.sign(sk, b"bench", bytes(range(32, 64)))
    sg = time.time() - t
    t = time.time()
    ok = mldsa.verify(pk, b"bench", sig)
    vf = time.time() - t
    check("bench verify", ok)
    print("bench: keygen %.2fs sign %.2fs verify %.2fs" % (kg, sg, vf))


if __name__ == "__main__":
    test_kat_keygen()
    test_kat_sign()
    test_kat_verify()
    test_self_consistency()
    test_ntt_roundtrip()
    test_decompose_identity()
    test_pack_roundtrips()
    test_bench()
    print("ALL %d CHECKS PASS" % len(PASS))
