import { Link } from "react-router-dom";
import { PageHead } from "@/components/PageHead";

const UPDATED = "June 3, 2026";

function Shell({ title, description, path, children }: { title: string; description: string; path: string; children: React.ReactNode }) {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <PageHead title={`${title} — Aetherion Oracle`} description={description} path={path} />

      <header className="border-b border-[hsl(186_90%_55%/0.18)] bg-[hsl(260_45%_3%/0.85)] backdrop-blur">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-5 py-4">
          <Link to="/" className="font-saga neon-block text-lg tracking-wider">AETHERION</Link>
          <Link to="/" className="font-tech text-[11px] text-[hsl(var(--neon-cyan))] hover:underline">
            &lt; RETURN
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-5 py-12">
        <h1 className="font-saga neon-block mb-2 text-3xl sm:text-4xl">{title}</h1>
        <p className="mb-10 font-tech text-[11px] text-muted-foreground">
          LAST UPDATED :: {UPDATED}
        </p>
        <article className="prose prose-invert max-w-none font-crt text-lg leading-relaxed text-foreground/85 [&_h2]:font-saga [&_h2]:text-[hsl(var(--neon-cyan))] [&_h2]:mt-10 [&_h2]:mb-3 [&_h2]:text-xl [&_a]:text-[hsl(var(--neon-magenta))] [&_a]:underline [&_p]:mb-4 [&_ul]:mb-4 [&_ul]:list-disc [&_ul]:pl-6 [&_li]:mb-1">
          {children}
        </article>

        <footer className="mt-16 flex flex-wrap items-center justify-between gap-3 border-t border-[hsl(186_90%_55%/0.15)] pt-6 font-tech text-[10px] uppercase tracking-widest text-muted-foreground/70">
          <span>© {new Date().getFullYear()} UnicornOS · Aetherion</span>
          <span className="flex gap-4">
            <Link to="/terms" className="hover:text-[hsl(var(--neon-cyan))]">Terms</Link>
            <Link to="/privacy" className="hover:text-[hsl(var(--neon-cyan))]">Privacy</Link>
            <Link to="/refund" className="hover:text-[hsl(var(--neon-cyan))]">Refund</Link>
            <a href="mailto:support@aetherion.lovable.app" className="hover:text-[hsl(var(--neon-cyan))]">Contact</a>
          </span>
        </footer>
      </main>
    </div>
  );
}

export const Terms = () => (
  <Shell title="Terms of Service" description="Aetherion's Terms of Service: subscriptions, acceptable use, intellectual property, disclaimers, and limits of liability." path="/terms">

    <p>
      Welcome to Aetherion (the "Service"), operated by UnicornOS ("we", "us"). By
      creating an account or using the Service you agree to these Terms. If you do
      not agree, do not use the Service.
    </p>

    <h2>1. The Service</h2>
    <p>
      Aetherion is an AI-powered symbolic oracle. Responses are generated by
      large language models and are provided <strong>for entertainment, creative,
      and reflective purposes only</strong>. They are not professional advice
      (medical, legal, financial, psychological, or otherwise). Do not rely on
      the Oracle for decisions that affect your health, safety, finances, or
      legal status.
    </p>

    <h2>2. Eligibility &amp; Account</h2>
    <p>
      You must be at least 16 years old (or the age of digital consent in your
      jurisdiction). You are responsible for safeguarding your password and for
      all activity under your account.
    </p>

    <h2>3. Subscriptions, Credits &amp; Billing</h2>
    <ul>
      <li>Free tier ("Seeker") includes a daily and monthly quota.</li>
      <li>Paid tiers ("Acolyte", "Oracle Pro") are billed monthly via Stripe.</li>
      <li>Subscriptions renew automatically until cancelled. You can cancel at any time from your account; access continues through the end of the paid period.</li>
      <li>Promotional passes and referral credits have no cash value.</li>
    </ul>

    <h2>4. Acceptable Use</h2>
    <p>You agree not to:</p>
    <ul>
      <li>Use the Service to generate content that is illegal, harmful, harassing, sexually explicit involving minors, or that infringes third-party rights.</li>
      <li>Attempt to bypass quotas, reverse engineer, scrape, or overload the Service.</li>
      <li>Use outputs to make medical, legal, or safety-critical decisions.</li>
    </ul>
    <p>We may suspend or terminate accounts that violate these rules.</p>

    <h2>5. Intellectual Property</h2>
    <p>
      The Service, including its design, brand, code, and prompts, is owned by
      UnicornOS. You own the Words of Power you submit. Oracle responses are
      provided to you under a personal, non-exclusive license; you may share them
      with attribution.
    </p>

    <h2>6. Disclaimers</h2>
    <p>
      THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. AI OUTPUTS
      MAY BE INACCURATE OR HALLUCINATED. WE DISCLAIM ALL IMPLIED WARRANTIES TO
      THE FULLEST EXTENT PERMITTED BY LAW.
    </p>

    <h2>7. Limitation of Liability</h2>
    <p>
      TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY FOR ANY CLAIM
      ARISING OUT OF THE SERVICE IS LIMITED TO THE AMOUNT YOU PAID US IN THE 12
      MONTHS PRECEDING THE CLAIM. WE ARE NOT LIABLE FOR INDIRECT, INCIDENTAL,
      OR CONSEQUENTIAL DAMAGES.
    </p>

    <h2>8. Changes</h2>
    <p>
      We may update these Terms. Material changes will be announced in-app or by
      email. Continued use after changes means acceptance.
    </p>

    <h2>9. Contact</h2>
    <p>
      Questions: <a href="mailto:support@aetherion.lovable.app">support@aetherion.lovable.app</a>
    </p>
  </Shell>
);

export const Privacy = () => (
  <Shell title="Privacy Policy" description="What data Aetherion collects, why we use it, how we share it, and your GDPR / CCPA rights." path="/privacy">

    <p>
      This policy explains what data Aetherion collects, why, and your rights.
    </p>

    <h2>1. Data We Collect</h2>
    <ul>
      <li><strong>Account data</strong> — email, display name, avatar (if signed in via Google), password hash.</li>
      <li><strong>Usage data</strong> — the Words of Power you submit, Oracle responses, model selection, daily/monthly query counts.</li>
      <li><strong>Billing data</strong> — handled by Stripe. We store the Stripe customer ID, subscription tier, invoice metadata. We never see or store card numbers.</li>
      <li><strong>Optional data</strong> — wallet address (if you connect one for mining).</li>
      <li><strong>Technical</strong> — basic logs (IP, user agent, timestamps) for security and abuse prevention.</li>
    </ul>

    <h2>2. How We Use It</h2>
    <ul>
      <li>Operate the Oracle, enforce quotas, and personalize your codex.</li>
      <li>Process payments and manage subscriptions.</li>
      <li>Detect abuse, debug issues, improve the Service.</li>
      <li>Send transactional emails (auth, billing). No marketing without consent.</li>
    </ul>

    <h2>3. AI Processing</h2>
    <p>
      Words of Power are sent to AI model providers (Google Gemini, OpenAI via
      Lovable AI Gateway) to generate responses. Providers process inputs under
      their own policies and are contractually prohibited from using your data
      to train their models.
    </p>

    <h2>4. Sharing</h2>
    <p>We share data only with:</p>
    <ul>
      <li>Stripe (payments), Supabase / Lovable Cloud (hosting + database), AI model providers (response generation), Alchemy (RPC for wallet features).</li>
      <li>Law enforcement when legally required.</li>
    </ul>
    <p>We do not sell personal data.</p>

    <h2>5. Retention</h2>
    <p>
      Account and usage data are retained while your account is active and for
      up to 30 days after deletion (for backups and abuse investigation). Billing
      records are kept as long as required by tax law.
    </p>

    <h2>6. Your Rights</h2>
    <p>
      You can access, export, or delete your data by emailing
      <a href="mailto:support@aetherion.lovable.app"> support@aetherion.lovable.app</a>.
      EU/UK residents have rights under GDPR (access, rectification, erasure,
      portability, objection). California residents have rights under CCPA.
    </p>

    <h2>7. Cookies</h2>
    <p>
      We use first-party cookies and localStorage for authentication and tier
      state. No advertising or cross-site tracking cookies.
    </p>

    <h2>8. Children</h2>
    <p>The Service is not directed to children under 16.</p>

    <h2>9. Contact</h2>
    <p><a href="mailto:support@aetherion.lovable.app">support@aetherion.lovable.app</a></p>
  </Shell>
);

export const Refund = () => (
  <Shell title="Refund Policy" description="Aetherion's refund policy for monthly subscriptions, including the 7-day, 25%-quota refund window." path="/refund">

    <h2>Subscriptions</h2>
    <p>
      Aetherion subscriptions are billed monthly in advance. You may cancel at
      any time from your account — your access continues through the end of the
      paid period and you are not charged again.
    </p>

    <h2>Refund Requests</h2>
    <p>
      We offer a refund of the most recent monthly charge if:
    </p>
    <ul>
      <li>You request it within <strong>7 days</strong> of the charge, and</li>
      <li>You have used fewer than 25% of your tier's monthly quota.</li>
    </ul>
    <p>
      Outside of these conditions, charges are non-refundable. Promotional
      passes, referral credits, and one-time fees are non-refundable.
    </p>

    <h2>How to Request</h2>
    <p>
      Email <a href="mailto:support@aetherion.lovable.app">support@aetherion.lovable.app</a> from
      the address on your account with your invoice ID. We respond within 5
      business days. Approved refunds are issued to the original payment method
      via Stripe and typically appear within 5–10 business days.
    </p>

    <h2>Service Issues</h2>
    <p>
      If a verified outage or billing error caused you not to receive the
      Service you paid for, we will refund or credit the affected period in full
      regardless of the conditions above.
    </p>
  </Shell>
);

const LEGAL_LINKS = [
  { href: "/terms", title: "Terms of Service", blurb: "Subscriptions, acceptable use, IP, disclaimers." },
  { href: "/privacy", title: "Privacy Policy", blurb: "What we collect, how we use it, your rights." },
  { href: "/refund", title: "Refund Policy", blurb: "Monthly billing, cancellation, refund window." },
];

export const LegalHub = () => (
  <Shell
    title="Legal"
    description="Aetherion legal hub — terms of service, privacy policy, and refund policy."
    path="/legal"
  >
    <p>
      Policies for Aetherion Oracle operated by UnicornOS. Choose a document below.
    </p>
    <ul className="!list-none !pl-0 space-y-3">
      {LEGAL_LINKS.map((l) => (
        <li key={l.href}>
          <Link to={l.href} className="block rounded-md border border-border px-4 py-3 hover:bg-muted/40">
            <span className="font-saga text-[hsl(var(--neon-cyan))]">{l.title}</span>
            <span className="mt-1 block text-sm text-muted-foreground">{l.blurb}</span>
          </Link>
        </li>
      ))}
    </ul>
    <p className="mt-8">
      Questions: <a href="mailto:support@aetherion.lovable.app">support@aetherion.lovable.app</a>
    </p>
  </Shell>
);
